DIR = "E:\\ragbot\\redberyl_tech_all_data.txt"
DATA_FILE = "../redberyl_tech_all_data.txt"
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
OLLAMA_MODEL_NAME = "tinyllama"
OLLAMA_BASE_URL = "http://127.0.0.1:11434"
PROMPT_TEMPLATE = """Use ONLY the information in the context to answer the question. Output ONLY the answer text—do not repeat the question, do not add any explanation, and do not include any preamble.\n\nContext:\n{context}\n\nQuestion: {question}\n\nAnswer:"""
INSUFFICIENT_ANSWER_RESPONSE = "Sorry, I could not get the answer to your question from the available information."
PRICE_INQUIRY_RESPONSE = "For  pricing and commercial details, please contact RedBeryl Technologies directly at their official channels."